import type { Product } from "@/types";
import { colors as C, sizes as S } from "./categories";

/**
 * کاتالوگ محصولات — داده اولیه (Seed فاز 2)
 * توضیحات انسانی طبق پرامپت 33: جنس، حس لمس، جذب، وزن، کاربرد، نگهداری.
 *
 * ADR 011: برچسب‌ها (پرفروش/جدید/محدود) دیگر در seed نیستند — محاسباتی‌اند.
 * تاریخ افزودن هم نسبی است (daysAgo) تا قانون «جدید» در هر زمان دموی واقعی بدهد.
 */
export type SeedProduct = Omit<Product, "badges" | "createdAt"> & { daysAgo: number };

export const products: SeedProduct[] = [
  {
    id: "p1",
    slug: "prima-bath-towel",
    name: "حوله حمام پریما",
    shortDescription: "حوله حمام ۵۵۰ گرمی با جذب بالا و حس نرم روی پوست",
    description:
      "بافت متراکم و لطیف این حوله برای استفاده روزمره طراحی شده و ترکیبی از جذب مناسب و حس نرم روی پوست ارائه می‌دهد. الیاف صددرصد پنبه شانه‌شده حلقه‌ای بلند، آب را چند برابر وزن خود جذب می‌کنند و پس از هر شست‌وشو، نرمی اولیه خود را حفظ می‌کنند. لبه‌های دوسوزنه‌ای مقاوم از باز شدن درز در استفاده طولانی‌مدت جلوگیری می‌کنند. این حوله بعد از چند بار استفاده، کمی وازنی‌تر و نرم‌تر می‌شود؛ همان حسی که از یک حوله باکیفیت انتظار دارید.",
    price: 745_000,
    compareAtPrice: 890_000,
    sku: "PRM-BT-70140-CRM",
    categorySlug: "bath-towels",
    collectionSlugs: ["premium", "everyday"],
    images: ["/images/p-cream.jpg", "/images/p-hook.jpg", "/images/lifestyle-shelf.jpg"],
    colors: [C.cream, C.white, C.taupe, C.sage],
    sizes: [S.bath, S.bathLarge],
    specs: [
      { label: "جنس", value: "۱۰۰٪ پنبه شانه‌شده" },
      { label: "وزن", value: "۵۵۰ گرم بر متر مربع" },
      { label: "سایز", value: "۷۰ × ۱۴۰ سانتی‌متر" },
      { label: "نوع بافت", value: "حلقه‌ای (Terry)" },
      { label: "جذب آب", value: "بالا" },
      { label: "تولید", value: "ایران" },
    ],
    care: [
      "شست‌وشو با آب سرد یا ولرم (حداکثر ۴۰ درجه)",
      "از نرم‌کننده استفاده نکنید؛ نرم‌کننده جذب الیاف را کم می‌کند",
      "خشک‌کردن در سایه یا خشک‌کن دمای پایین",
      "برای حفظ لطافت، گاه‌به‌گاه با کمی سرکه سفید بشویید",
    ],
    suitableFor: [
      "استفاده روزمره خانواده",
      "کسانی که حوله نرم و جذب بالا می‌خواهند",
      "خانه جدید و جهیزیه",
    ],
    features: ["جذب سریع", "بافت متراکم", "دوسوزنه مقاوم", "بدون ریزش"],
    stock: 32,
    status: "ACTIVE",
    rating: 4.8,
    reviewCount: 127,
    order: 1,
    daysAgo: 95,
  },
  {
    id: "p2",
    slug: "prima-bath-towel-taupe",
    name: "حوله حمام پریما — خاکستری گرم",
    shortDescription: "همان حوله محبوب پریما در رنگ خاکستری گرم و آرام",
    description:
      "رنگ خاکستری گرم این حوله با هر دکور حمامی — از سنگی تا چوبی — هماهنگ می‌شود. بافت حلقه‌ای متراکم آن، همان لطافت و جذب حوله پریما را دارد و برای کسانی که رنگ‌های خنثی را انتخاب می‌کنند، گزینه‌ای بی‌ریسک است. وزن ۵۵۰ گرم بر متر مربع آن، تعادلی است بین حس سنگین و پریمیوم بودن و سرعت خشک‌شدن؛ یعنی حوله‌ای که نه سبک و بی‌کیفیت به نظر می‌رسد، نه آن‌قدر سنگین است که در هوای مرطوب خشک نشود.",
    price: 745_000,
    sku: "PRM-BT-70140-TP",
    categorySlug: "bath-towels",
    collectionSlugs: ["premium", "everyday"],
    images: ["/images/p-taupe.jpg", "/images/p-warm-stack.jpg", "/images/lifestyle-wood.jpg"],
    colors: [C.taupe, C.cream, C.stone],
    sizes: [S.bath, S.bathLarge],
    specs: [
      { label: "جنس", value: "۱۰۰٪ پنبه شانه‌شده" },
      { label: "وزن", value: "۵۵۰ گرم بر متر مربع" },
      { label: "سایز", value: "۷۰ × ۱۴۰ سانتی‌متر" },
      { label: "نوع بافت", value: "حلقه‌ای (Terry)" },
      { label: "جذب آب", value: "بالا" },
      { label: "تولید", value: "ایران" },
    ],
    care: [
      "شست‌وشو با آب سرد یا ولرم (حداکثر ۴۰ درجه)",
      "از نرم‌کننده استفاده نکنید",
      "خشک‌کردن در سایه یا خشک‌کن دمای پایین",
      "رنگ‌های تیره را جداگانه بشویید",
    ],
    suitableFor: ["دکور مینیمال و خنثی", "استفاده روزمره", "سرویس مهمان خانه"],
    features: ["جذب سریع", "رنگ ثابت", "بافت متراکم"],
    stock: 18,
    status: "ACTIVE",
    rating: 4.7,
    reviewCount: 64,
    order: 2,
    daysAgo: 90,
  },
  {
    id: "p3",
    slug: "prima-hand-face-towel",
    name: "حوله دست و صورت آرین",
    shortDescription: "حوله دست و صورت لطیف با بافت ظریف برای پوست حساس",
    description:
      "این حوله برای تماس روزانه با پوست صورت بافته شده است؛ الیاف آن ظریف‌تر و حلقه‌ها کوتاه‌تر از حوله حمام هستند تا حس نرمی ملایم‌تری به پوست بدهند. وزن ۵۰۰ گرم بر متر مربع آن به‌اندازه‌ای است که بعد از استفاده سریع خشک می‌شود و برای بهداشت پوست، توصیه می‌شود هر چند روز یک‌بار عوض شود. سایز ۳۵ × ۷۵ برای آویزان‌شدن روی رینگ یا دستگیره حمام اندازه استاندارد دارد.",
    price: 285_000,
    sku: "PRM-HF-3575-BGE",
    categorySlug: "hand-face",
    collectionSlugs: ["everyday", "premium"],
    images: ["/images/p-beige.jpg", "/images/p-vanity.jpg"],
    colors: [C.beige, C.white, C.cream, C.mint],
    sizes: [S.hand, S.handSmall],
    specs: [
      { label: "جنس", value: "۱۰۰٪ پنبه" },
      { label: "وزن", value: "۵۰۰ گرم بر متر مربع" },
      { label: "سایز", value: "۳۵ × ۷۵ سانتی‌متر" },
      { label: "نوع بافت", value: "حلقه‌ای ظریف" },
      { label: "مناسب برای", value: "پوست حساس" },
      { label: "تولید", value: "ایران" },
    ],
    care: [
      "هر ۲ تا ۳ روز یک‌بار تعویض شود",
      "شست‌وشو با آب ولرم و مایع ملایم",
      "از اتوی داغ پرهیز کنید",
    ],
    suitableFor: ["مراقبت روزانه پوست", "سرویس حمام مهمان", "بسته‌های هدیه"],
    features: ["الیاف ظریف", "سریع‌الخشک", "ضدحساسیت"],
    stock: 54,
    status: "ACTIVE",
    rating: 4.9,
    reviewCount: 91,
    order: 3,
    daysAgo: 120,
  },
  {
    id: "p4",
    slug: "prima-guest-towel-striped",
    name: "حوله مهمان راه‌راه",
    shortDescription: "حوله مهمان بافت وافل با راه‌راه محو، سبک و شیک",
    description:
      "حوله مهمان بافت وافل سبک است، سریع خشک می‌شود و بافت مشبک آن ظاهری ادیتوریال به سرویس بهداشتی می‌دهد. راه‌راه‌های محو آن با رنگ‌های کرم و شنی، برای دستشویی مهمان که می‌خواهید متفاوت و مرتب باشد انتخاب شده است. چون بافت وافل نسبت به بافت حلقه‌ای لطافت کمتری دارد، این حوله برای خشک‌کردن سریع دست طراحی شده، نه استفاده حمامی سنگین.",
    price: 195_000,
    sku: "PRM-GT-4060-STR",
    categorySlug: "hand-face",
    collectionSlugs: ["seasonal", "everyday"],
    images: ["/images/p-stripe.jpg", "/images/p-hook.jpg"],
    colors: [C.cream, C.sand],
    sizes: [S.guest],
    specs: [
      { label: "جنس", value: "۱۰۰٪ پنبه" },
      { label: "وزن", value: "۴۵۰ گرم بر متر مربع" },
      { label: "سایز", value: "۴۰ × ۶۰ سانتی‌متر" },
      { label: "نوع بافت", value: "وافل (Waffle)" },
      { label: "مناسب برای", value: "سرویس بهداشتی مهمان" },
      { label: "تولید", value: "ایران" },
    ],
    care: ["شست‌وشو با آب سرد", "اتوی ملایم در صورت نیاز", "خشک‌کردن سریع روی بند"],
    suitableFor: ["دستشویی مهمان", "آشپزخانه", "سفر و پیک‌نیک"],
    features: ["بافت وافل", "سریع‌الخشک", "سبک"],
    stock: 40,
    status: "ACTIVE",
    rating: 4.6,
    reviewCount: 38,
    order: 4,
    daysAgo: 6,
  },
  {
    id: "p5",
    slug: "prima-pool-towel",
    name: "حوله استخری ساحل",
    shortDescription: "حوله استخری بزرگ ۹۰×۱۸۰ با رنگ‌های روشن ساحلی",
    description:
      "این حوله برای کنار استخر و ساحل طراحی شده است؛ ابعاد بزرگ ۹۰ × ۱۸۰ آن روی صندلی استخر یا چمن می‌نشیند و پهنای کافی برای خشک‌کردن کامل بدن دارد. الیاف حلقه‌ای متراکم آن در برابر کلر و نور آفتاب مقاوم‌تر از حوله‌های حمام معمولی است و رنگ‌های روشن آن زیر آفتاب گرم نمی‌شود. وزن ۴۵۰ گرم بر متر مربع یعنی حوله‌ای که در باد ملایم ساحل می‌خشکد و بعد از استخر، بدن را به‌سرعت جمع می‌کند.",
    price: 980_000,
    sku: "PRM-PT-90180-BCH",
    categorySlug: "pool",
    collectionSlugs: ["seasonal", "everyday"],
    images: ["/images/p-lake.jpg", "/images/lifestyle-beach.jpg", "/images/cat-pool.jpg"],
    colors: [C.white, C.cream, C.sand],
    sizes: [S.pool],
    specs: [
      { label: "جنس", value: "۱۰۰٪ پنبه" },
      { label: "وزن", value: "۴۵۰ گرم بر متر مربع" },
      { label: "سایز", value: "۹۰ × ۱۸۰ سانتی‌متر" },
      { label: "نوع بافت", value: "حلقه‌ای متراکم" },
      { label: "مقاومت", value: "مناسب کلر و آفتاب" },
      { label: "تولید", value: "ایران" },
    ],
    care: [
      "بعد از هر استفاده در استخر، با آب شیرین بشویید",
      "شست‌وشو با آب سرد تا حفظ رنگ",
      "در سایه خشک کنید",
    ],
    suitableFor: ["استخر و ساحل", "باشگاه و ورزش آبی", "ویلا و حیاط"],
    features: ["ابعاد بزرگ", "مقاوم به کلر", "سریع‌الخشک"],
    stock: 22,
    status: "ACTIVE",
    rating: 4.7,
    reviewCount: 45,
    order: 5,
    daysAgo: 60,
  },
  {
    id: "p6",
    slug: "prima-white-hotel-towel",
    name: "حوله حمام سفید هتلی",
    shortDescription: "حوله سفید ۶۰۰ گرمی با حس هتل پنج‌ستاره در خانه",
    description:
      "همان حوله‌ای که در هتل‌های خوب لمس می‌کنید؛ وزن ۶۰۰ گرم بر متر مربع، بافت حلقه‌ای بلند و سفید روشنی که با هر شست‌وشو سفیدتر می‌ماند. این حوله برای کسانی است که حوله را «تجربه» می‌دانند، نه یک وسیله؛ سنگینی متعادل آن روی شانه‌ها بعد از دوش، حس پوشش کامل و گرم می‌دهد. سفید بودن آن بهداشتی‌ترین انتخاب برای سرویس مهمان است و با شوینده‌های ملایم رنگی، جرم نمی‌گیرد.",
    price: 1_190_000,
    sku: "PRM-HT-70140-WHT",
    categorySlug: "bath-towels",
    collectionSlugs: ["premium", "spa"],
    images: ["/images/cat-bath.jpg", "/images/cat-hand.jpg", "/images/lifestyle-candle.jpg"],
    colors: [C.white],
    sizes: [S.bath, S.bathLarge],
    specs: [
      { label: "جنس", value: "۱۰۰٪ پنبه شانه‌شده" },
      { label: "وزن", value: "۶۰۰ گرم بر متر مربع" },
      { label: "سایز", value: "۷۰ × ۱۴۰ سانتی‌متر" },
      { label: "نوع بافت", value: "حلقه‌ای بلند" },
      { label: "جذب آب", value: "بسیار بالا" },
      { label: "تولید", value: "ایران" },
    ],
    care: [
      "شست‌وشوی جداگانه با شوینده سفید",
      "حداکثر دمای ۶۰ درجه برای بهداشت کامل",
      "از سفیدکننده کلری به‌صورت مداوم استفاده نکنید",
    ],
    suitableFor: ["عاشقان حس هتل", "سرویس مهمان", "اسپای خانگی"],
    features: ["وزن سنگین", "سفیدی ماندگار", "جذب بسیار بالا"],
    stock: 15,
    status: "ACTIVE",
    rating: 4.9,
    reviewCount: 73,
    order: 6,
    daysAgo: 75,
  },
  {
    id: "p7",
    slug: "prima-towel-set-4pcs",
    name: "ست ۴ تکه خانه نو",
    shortDescription: "ست کامل: ۲ حوله حمام + ۲ حوله دست و صورت، هم‌رنگ",
    description:
      "این ست برای کسانی است که تازه خانه‌ای چیده‌اند یا سرویس حمام را یک‌جا نوسازی می‌کنند؛ دو حوله حمام ۷۰ × ۱۴۰ و دو حوله دست و صورت ۳۵ × ۷۵، همه در یک رنگ هماهنگ و با همان کیفیت حوله پریما. خرید ست، هم اقتصادی‌تر از خرید تک‌به‌تک است و هم تضمین می‌کند رنگ و بافت همه تکه‌ها با هم ساخته شده‌اند. بسته‌بندی ست با نوار کتان آماده هدیه دادن است.",
    price: 2_450_000,
    compareAtPrice: 2_780_000,
    sku: "PRM-SET-4-BGE",
    categorySlug: "sets",
    collectionSlugs: ["premium", "gift"],
    images: ["/images/cat-sets.jpg", "/images/p-cream.jpg", "/images/p-beige.jpg"],
    colors: [C.cream, C.beige, C.sage],
    sizes: [S.bath, S.hand],
    specs: [
      { label: "محتوی ست", value: "۲ حوله حمام + ۲ حوله دست و صورت" },
      { label: "جنس", value: "۱۰۰٪ پنبه شانه‌شده" },
      { label: "وزن", value: "۵۵۰ / ۵۰۰ گرم بر متر مربع" },
      { label: "بسته‌بندی", value: "جعبه هدیه با نوار کتان" },
      { label: "تولید", value: "ایران" },
    ],
    care: [
      "همه تکه‌ها با هم قابلیت شست‌وشو دارند",
      "شست‌وشو با آب ولرم و شوینده ملایم",
      "بدون نرم‌کننده برای حفظ جذب",
    ],
    suitableFor: ["خانه نو و جهیزیه", "هدیه عروسی", "نوسازی سرویس حمام"],
    features: ["بسته‌بندی هدیه", "هماهنگی رنگ کامل", "اقتصادی‌تر از خرید تکی"],
    stock: 12,
    status: "ACTIVE",
    rating: 4.8,
    reviewCount: 52,
    order: 7,
    daysAgo: 30,
  },
  {
    id: "p8",
    slug: "prima-warm-stack-set",
    name: "ست لایه‌ای گرم",
    shortDescription: "ست ۶ تکه در رنگ‌های گرم خاکستری و کرم",
    description:
      "ست لایه‌ای برای خانواده‌های چندنفره طراحی شده است؛ سه حوله حمام و سه حوله دست و صورت در طیف گرم خاکستری و کرم که روی هم چیده‌شده، یک ترکیب‌بندی زیبا در قفسه حمام می‌سازند. تکه‌های این ست در دو رنگ نزدیک به هم عرضه می‌شوند تا ظاهر ست، طبیعی و دکوراتیو بماند، نه سفت و یکدست. مناسب خانه‌هایی که حمام‌شان قفسه باز دارد و حوله‌ها بخشی از دکور هستند.",
    price: 3_250_000,
    sku: "PRM-SET-6-WRM",
    categorySlug: "sets",
    collectionSlugs: ["premium", "everyday"],
    images: ["/images/cat-gift.jpg", "/images/p-warm-stack.jpg", "/images/lifestyle-shelf.jpg"],
    colors: [C.taupe, C.cream],
    sizes: [S.bath, S.hand],
    specs: [
      { label: "محتوی ست", value: "۳ حوله حمام + ۳ حوله دست و صورت" },
      { label: "جنس", value: "۱۰۰٪ پنبه" },
      { label: "وزن", value: "۵۵۰ / ۵۰۰ گرم بر متر مربع" },
      { label: "پالت رنگ", value: "خاکستری گرم + کرم" },
      { label: "تولید", value: "ایران" },
    ],
    care: ["شست‌وشوی رنگ‌های متفاوت جدا از هم", "بدون نرم‌کننده", "خشک‌کردن در سایه"],
    suitableFor: ["خانواده‌های چندنفره", "حمام با قفسه باز", "دکور گرم و مینیمال"],
    features: ["۶ تکه کامل", "پالت هماهنگ", "قابل نمایش روی قفسه"],
    stock: 9,
    status: "ACTIVE",
    rating: 4.7,
    reviewCount: 29,
    order: 8,
    daysAgo: 50,
  },
  {
    id: "p9",
    slug: "prima-kids-towel",
    name: "حوله کودک ابری",
    shortDescription: "حوله کودک سبک و لطیف با الیاف ضدحساسیت",
    description:
      "پوست کودک نازک‌تر از پوست بزرگسال است، برای همین این حوله با الیاف ضدحساسیت و بدون رنگ‌های شیمیایی سنگین بافته شده است. وزن ۴۲۰ گرم بر متر مربع آن سبک است تا کودک خودش بتواند حوله را بگیرد و رویش را خشک کند — و همین استقلال کوچک، بخشی از لذت حمام کردن است. رنگ‌های ملایم آن برای اتاق کودک با هر تم رنگی آرام است.",
    price: 495_000,
    sku: "PRM-KD-60120-MNT",
    categorySlug: "kids",
    collectionSlugs: ["everyday"],
    images: ["/images/p-mint.jpg", "/images/cat-kids.jpg"],
    colors: [C.mint, C.cream, C.white],
    sizes: [S.kids],
    specs: [
      { label: "جنس", value: "۱۰۰٪ پنبه ارگانیک" },
      { label: "وزن", value: "۴۲۰ گرم بر متر مربع" },
      { label: "سایز", value: "۶۰ × ۱۲۰ سانتی‌متر" },
      { label: "تأییدیه", value: "بدون مواد مضر (OEKO-TEX استاندارد)" },
      { label: "مناسب برای", value: "۲ تا ۱۰ سال" },
      { label: "تولید", value: "ایران" },
    ],
    care: [
      "شست‌وشو با شوینده کودک ملایم",
      "دمای آب حداکثر ۴۰ درجه",
      "اتو نکشید",
    ],
    suitableFor: ["حمام روزانه کودک", "هدیه تولد کودک", "مهدکودک و خانه"],
    features: ["ضدحساسیت", "سبک", "بدون رنگ شیمیایی سنگین"],
    stock: 26,
    status: "ACTIVE",
    rating: 4.9,
    reviewCount: 61,
    order: 9,
    daysAgo: 20,
  },
  {
    id: "p10",
    slug: "prima-waffle-bathrobe",
    name: "تن‌پوش وافل آرام",
    shortDescription: "تن‌پوش وافل سبک با کمربند پارچه‌ای",
    description:
      "تن‌پوش وافل برای بعد از حمام یا استخر طراحی شده است؛ بافت مشبک وافل سبک است، هوا را رد می‌دهد و رطوبت را سریع تبخیر می‌کند، در نتیجه بعد از پوشیدن احساس چسبندگی و گرمازده‌شدن نمی‌کنید. جیب‌های دو طرف عمیق‌اند و کمربند پارچه‌ای آن قابل تنظیم است. این تن‌پوش در خانه، استخر یا سفر ویلا، جایگزین مینیمال و شیک حوله‌های بزرگ است.",
    price: 1_680_000,
    sku: "PRM-RB-WFL-GRY",
    categorySlug: "bathrobes",
    collectionSlugs: ["spa", "premium"],
    images: ["/images/cat-robe.jpg", "/images/p-robe-model.jpg", "/images/lifestyle-wood.jpg"],
    colors: [C.stone, C.white, C.sage],
    sizes: [
      { id: "robe-m", label: "M", dimensions: "قد ۱۲۰", gsm: 280 },
      { id: "robe-l", label: "L", dimensions: "قد ۱۲۵", gsm: 280 },
      { id: "robe-xl", label: "XL", dimensions: "قد ۱۳۰", gsm: 280 },
    ],
    specs: [
      { label: "جنس", value: "۱۰۰٪ پنبه بافت وافل" },
      { label: "وزن", value: "۲۸۰ گرم بر متر مربع" },
      { label: "جزئیات", value: "کمربند پارچه‌ای + ۲ جیب" },
      { label: "مناسب برای", value: "بعد از حمام و استخر" },
      { label: "تولید", value: "ایران" },
    ],
    care: ["شست‌وشو با آب ولرم", "اتوی ملایم برای حفظ بافت", "خشک‌کردن آویزان"],
    suitableFor: ["بعد از حمام روزانه", "استخر و باشگاه", "سفر ویلا"],
    features: ["سبک و تنفس‌پذیر", "سریع‌الخشک", "جیب عمیق"],
    stock: 14,
    status: "ACTIVE",
    rating: 4.8,
    reviewCount: 34,
    order: 10,
    daysAgo: 40,
  },
  {
    id: "p11",
    slug: "prima-spa-towel-set",
    name: "ست اسپای دو نفره",
    shortDescription: "حوله‌های لطیف با پالت اسپا برای حس ریکاوری",
    description:
      "این ست برای حس اسپا در خانه ساخته شده است؛ دو حوله بزرگ با بافت حلقه‌ای نرم در پالت روشن، همراه دو حوله صورت کوچک برای پاک‌سازی یا کمپرس گرم. تجربه‌ای که می‌سازد ساده است: چراغ را کم کنید، حوله را گرم کنید و پنج دقیقه آرامش را جدی بگیرید. پالت رنگی آن از طبیعت الهام گرفته است — کرم، سبز مریم‌گلی و سفید — تا حمام شما حس آسایش بدهد، نه شلوغی.",
    price: 2_950_000,
    sku: "PRM-SET-SPA-2",
    categorySlug: "sets",
    collectionSlugs: ["spa", "gift"],
    images: ["/images/lifestyle-candle.jpg", "/images/lifestyle-spa.jpg", "/images/cat-bath.jpg"],
    colors: [C.white, C.sage, C.cream],
    sizes: [S.bath, S.handSmall],
    specs: [
      { label: "محتوی ست", value: "۲ حوله حمام + ۲ حوله صورت" },
      { label: "جنس", value: "۱۰۰٪ پنبه شانه‌شده" },
      { label: "وزن", value: "۶۰۰ / ۴۸۰ گرم بر متر مربع" },
      { label: "پالت رنگ", value: "کرم، سفید، سبز مریم‌گلی" },
      { label: "تولید", value: "ایران" },
    ],
    care: ["شست‌وشو با شوینده ملایم", "بدون نرم‌کننده", "خشک‌کردن در سایه"],
    suitableFor: ["اسپای خانگی", "هدیه به خودتان", "هدیه جشن و تولد"],
    features: ["بافت ابریشمی", "پالت آرامش‌بخش", "بسته‌بندی هدیه"],
    stock: 8,
    status: "ACTIVE",
    rating: 4.9,
    reviewCount: 18,
    order: 11,
    daysAgo: 45,
  },
  {
    id: "p12",
    slug: "prima-travel-towel",
    name: "حوله مسافرتی سبک",
    shortDescription: "حوله فشرده و سبک برای سفر، باشگاه و استخر",
    description:
      "این حوله برای حمل‌شدن طراحی شده است؛ وزن ۴۰۰ گرم بر متر مربع آن نیم‌وزن‌تر از حوله حمام استاندارد است و تاشده‌اش در کوله باشگاه یا چمدان دستی جا می‌شود. بافت فشرده آن سریع خشک می‌شود — معمولاً تا شب — و بوی نم می‌گیرد. جذب آب آن به‌اندازه کافی خوب است، اما اگر حرفه‌ای شنا می‌کنید، حوله استخری بزرگ‌تر انتخاب بهتری است.",
    price: 420_000,
    sku: "PRM-TR-5090-CRM",
    categorySlug: "pool",
    collectionSlugs: ["everyday", "seasonal"],
    images: ["/images/p-rolled.jpg", "/images/p-lake.jpg"],
    colors: [C.cream, C.stone, C.mint],
    sizes: [S.travel],
    specs: [
      { label: "جنس", value: "۱۰۰٪ پنبه" },
      { label: "وزن", value: "۴۰۰ گرم بر متر مربع" },
      { label: "سایز", value: "۵۰ × ۹۰ سانتی‌متر" },
      { label: "نوع بافت", value: "فشرده" },
      { label: "مناسب برای", value: "سفر و باشگاه" },
      { label: "تولید", value: "ایران" },
    ],
    care: ["شست‌وشو با آب سرد", "خشک‌کردن سریع معلق", "بدون نرم‌کننده"],
    suitableFor: ["سفر و کمپ", "کیف باشگاه", "پشتیبان سرویس مهمان"],
    features: ["فشرده و سبک", "سریع‌الخشک", "قابل تا شدن کوچک"],
    stock: 48,
    status: "ACTIVE",
    rating: 4.5,
    reviewCount: 57,
    order: 12,
    daysAgo: 2,
  },
];
